actions: add improvements to get-latest-commit-sha
Add page to parse as a parameter with default value 20.
Check if returned variable is empty, if so fail execution.

Signed-off-by: Mateusz Redzynia <mateuszx.redzynia@intel.com>

diff --git a/actions/get-latest-commit-sha/action.yml b/actions/get-latest-commit-sha/action.yml
--- a/actions/get-latest-commit-sha/action.yml
+++ b/actions/get-latest-commit-sha/action.yml
@@ -40,7 +40,10 @@ inputs:
     description: 'fetch canceled run only'
     default: false
     type: boolean
-
+  pages-to-parse:
+    description: 'number of pages to parse'
+    default: 20
+    type: number
 
 runs:
   using: "composite"
@@ -54,17 +57,41 @@ runs:
     - name: 'Get succesful run commit sha'
       if: ${{ inputs.success == 'true' }}
       run: |
-        echo "LATEST_SUCCESSFUL_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-10] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="success") | .head_sha' | awk 'NR==1')" >> $GITHUB_ENV
+        LATEST_SUCCESSFUL_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-${{ inputs.pages-to-parse }}] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="success") | .head_sha' | awk 'NR==1')
+        
+        # Fail execution if LATEST_SUCCESSFUL_RUN_SHA is empty
+        if [[ -z "$LATEST_SUCCESSFUL_RUN_SHA" ]]; then
+          echo "LATEST_SUCCESSFUL_RUN_SHA is empty!"
+          exit 1
+        fi
+
+        echo "LATEST_SUCCESSFUL_RUN_SHA=$LATEST_SUCCESSFUL_RUN_SHA" >> $GITHUB_ENV
       shell: bash
 
     - name: 'Get failed run commit sha'
       if: ${{ inputs.failed == 'true' }}
       run: |
-        echo "LATEST_FAILED_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-10] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="failure") | .head_sha' | awk 'NR==1')" >> $GITHUB_ENV
+        LATEST_FAILED_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-${{ inputs.pages-to-parse }}] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="failure") | .head_sha' | awk 'NR==1')
+        
+        # Fail execution if LATEST_FAILED_RUN_SHA is empty
+        if [[ -z "$LATEST_FAILED_RUN_SHA" ]]; then
+          echo "LATEST_FAILED_RUN_SHA is empty!"
+          exit 1
+        fi
+
+        echo "LATEST_FAILED_RUN_SHA=$LATEST_FAILED_RUN_SHA" >> $GITHUB_ENV
       shell: bash
 
     - name: 'Get cancelled run commit sha'
       if: ${{ inputs.cancelled == 'true' }}
       run: |
-        echo "LATEST_CANCELLED_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-10] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="cancelled") | .head_sha' | awk 'NR==1')" >> $GITHUB_ENV
+        LATEST_CANCELLED_RUN_SHA=$(curl -u ${{ inputs.user }}:${{ inputs.token }} -s -H "Content-Type: application/json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow }}/runs?page=[1-${{ inputs.pages-to-parse }}] | jq -r '.workflow_runs[] | select(.event=="push" and .head_branch=="${{ inputs.branch }}" and .conclusion=="cancelled") | .head_sha' | awk 'NR==1')
+
+        # Fail execution if LATEST_CANCELLED_RUN_SHA is empty
+        if [[ -z "$LATEST_CANCELLED_RUN_SHA" ]]; then
+          echo "LATEST_CANCELLED_RUN_SHA is empty!"
+          exit 1
+        fi
+
+        echo "LATEST_CANCELLED_RUN_SHA=$LATEST_CANCELLED_RUN_SHA" >> $GITHUB_ENV
       shell: bash
